### ISSUE TITLE
Error during "init"

### ISSUE THREAD

**Issue by carman247** [freshworks/freshchat-flutter-sdk#5]
## Describe the bug
Not quite sure what's going on but getting strange error when trying to init Freshchat

## Steps to reproduce
```    
Freshchat.init('appId', 'appKey', 'domain');
```

## Platform
- [x] Android

## Freshchat SDK version
- SDK version : 0.4.0 
- Flutter version (if applicable) : 2.0.3

## Device information
```
Provide device details here like
 * Xiaomi Mi 9T Pro
 * Android API 10 (29)

```

## Crash log
```
E/FRESHCHAT(22677): Exception on Xiaomi Mi 9T Pro Android API 10 (29) >>>>> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/FRESHCHAT(22677): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/FRESHCHAT(22677): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/FRESHCHAT(22677): 	at com.google.gson.Gson.fromJson(Gson.java:932)
E/FRESHCHAT(22677): 	at com.google.gson.Gson.fromJson(Gson.java:897)
E/FRESHCHAT(22677): 	at com.google.gson.Gson.fromJson(Gson.java:846)
E/FRESHCHAT(22677): 	at com.google.gson.Gson.fromJson(Gson.java:817)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.j.ab.fromJson(Unknown Source:2)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.e.a.a(Unknown Source:7)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.e.a.cX(Unknown Source:25)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:15)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:2)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source:45)
E/FRESHCHAT(22677): 	at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source:90)
E/FRESHCHAT(22677): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
E/FRESHCHAT(22677): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/FRESHCHAT(22677): 	at android.os.Looper.loop(Looper.java:224)
E/FRESHCHAT(22677): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/FRESHCHAT(22677): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/FRESHCHAT(22677): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
E/FRESHCHAT(22677): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
E/FRESHCHAT(22677): 	... 15 more
```

**Comment by rameshfreshworks** [comment]
Hi @carman247
This crash is a known case and is caught. It does not hamper Freshchat functionality in anyway.
You can ignore this crash. Let us know otherwise!

**Comment by carman247** [comment]
> Hi @carman247
> This crash is a known case and is caught. It does not hamper Freshchat functionality in anyway.
> You can ignore this crash. Let us know otherwise!

Ok great! Thanks :)
